name: Snake

on:
  schedule:
    - cron: '0 * * * *'
    - workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the snake
        run: python HannaRF/snake.py
        working-directory: ${{ github.workspace }}
